name: test

on:
  push:
  pull_request:

jobs:
  unittest:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python: ["3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
      - run: python -m unittest -v
      - run: python -m compileall -q wcl_report_data tests
